name: Bump version in /server on merge to main

on:
  push:
    branches:
      - main
    # paths:
    #  - 'server/**'  # solo se activa si se modifica algo dentro de /server

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
