name: Bump version in /server on merge to main

on:
  push:
    branches:
      - main
    # paths:
    #  - 'server/**'  # solo se activa si se modifica algo dentro de /server

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump patch version
        run: |
          # Realizamos el bump de versión (patch por defecto)
          NEW_VERSION=$(npm version patch -m "ci: bump version to %s")
          echo "New version: $NEW_VERSION"
          # Extraemos la nueva versión y la usamos como tag
          VERSION_TAG=$(echo $NEW_VERSION | sed 's/^v//')  # Eliminar la 'v' de la versión (opcional)
          git tag v$VERSION_TAG
          git push --follow-tags

      - name: Push changes
        run: |
          git push origin main
